run:
  go: '1.22.5'
  build-tags:
    - integration_test
  tests: false

issues:
  exclude-dirs:
    - internal/mocks

linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - revive
    - sloglint
    - staticcheck
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/victorm/equiz
  revive:
    enable-all-rules: true
    rules:
      - name: add-constant
        severity: warning
        disabled: true
      - name: cognitive-complexity
        arguments: [ 11 ]
      - name: line-length-limit
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: nested-structs
        severity: warning
        disabled: true
  sloglint:
    context: "all"
    forbidden-keys:
      - time
      - level
      - msg